name: train-and-validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Download go dependencies
        run: go mod download
     
      - name: Install Dagger CLI
        run: |
         curl -L https://dl.dagger.io/dagger/install.sh | sh
         export PATH="$PWD/bin:$PATH"
         echo "$PWD/bin" >> $GITHUB_PATH
         dagger version

      - name: Run training pipeline with Dagger
        run: dagger run go run ./dagger/main.go

      - name: Prepare model artifact for validator
        run: |
          mkdir -p model
          cp notebooks/artifacts/lead_model_lr.pkl model/model.pkl

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4  
        with:
          name: model
          path: model/model.pkl

      - name: Upload full artifacts bundle
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: notebooks/artifacts

  validate:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: model

      - name: Run model validator
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
        with:
          model-path: artifacts/lead_model_lr.pkl
